version: "3.4"

services:
  jikan-rest:
    build:
      context: .
    volumes:
      - "./.env:/var/www/html/.env"
      - "./run-jikan.sh:/var/www/html/run-jikan.sh"
    ports:
      - "9000:80"
    networks:
      - default
    restart: always
    image: jikan-rest-img
    container_name: jikan-rest-api
